environment:
  matrix:
    - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm@latest
  - npm install -g yarn
  - yarn

test_script:
  - node --version
  - yarn --version
  - yarn test

build: off